"use client";

import { use, useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { getUsage, type Usage } from "@/lib/usage";
import { saveBlob } from "@/lib/saveBlob";
import { packFromRow, prepPdfFilename, type PrepPack } from "@/lib/prepPack";
import { loadPrepProgress, savePrepProgress, type PrepRating, type PrepRatings } from "@/lib/prepProgress";
import AppHeader from "@/components/ui/AppHeader";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import EmptyState from "@/components/ui/EmptyState";
import Skeleton from "@/components/ui/Skeleton";
import StatusText from "@/components/ui/StatusText";
import Badge from "@/components/ui/Badge";
import PrepPackView, { formatGenerated } from "./PrepPackView";
import PracticeMode from "./PracticeMode";

// Stage 4 — /applications/[id]/prep. One tracker row → one prep pack
// (generated by /api/prep, cached on the row) → read it, or drill it in
// practice mode. Deep-linkable: the auth proxy already protects /applications/*.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SESSION_EXPIRED = "Your session has expired — sign in again to see your prep pack.";

type Row = {
  id: string;
  company_name: string;
  role: string;
  status: string;
  job_description: string | null;
};

type LoadState = "loading" | "ready" | "missing" | "expired" | "error";

const STAGES = [
  "Reading the job description and your CV",
  "Matching their stack to your real experience",
  "Writing STAR answers from what you actually did",
  "Tracing every claim back to your CV",
];

export default function PrepPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);

  const [load, setLoad] = useState<LoadState>("loading");
  const [row, setRow] = useState<Row | null>(null);
  const [pack, setPack] = useState<PrepPack | null>(null);
  const [warning, setWarning] = useState("");
  const [usage, setUsage] = useState<Usage | null>(null);
  const [userId, setUserId] = useState<string | null>(null);

  const [ratings, setRatings] = useState<PrepRatings>({});
  const [practicing, setPracticing] = useState(false);
  const practiceBtnRef = useRef<HTMLButtonElement>(null);
  const restoreFocus = useRef(false);

  const [generating, setGenerating] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState("");
  const [errorType, setErrorType] = useState<string | null>(null);
  const [confirmRegen, setConfirmRegen] = useState(false);
  const [pdfBusy, setPdfBusy] = useState(false);
  const [pdfError, setPdfError] = useState("");

  // ── Load the row (and any cached pack) ──────────────────────────────────────
  useEffect(() => {
    let active = true;
    async function run() {
      if (!UUID_RE.test(id)) {
        setLoad("missing");
        return;
      }
      const supabase = createClient();
      const { data: { session } } = await supabase.auth.getSession();
      if (active) setUserId(session?.user?.id ?? null);
      try {
        const res = await fetch(`/api/applications?id=${encodeURIComponent(id)}`);
        const data = await res.json().catch(() => ({}));
        if (!active) return;
        if (res.status === 401) { setLoad("expired"); return; }
        if (res.status === 404) { setLoad("missing"); return; }
        if (!res.ok) { setError(data.error || "Couldn't load this application."); setLoad("error"); return; }
        const app = data.application as Row & { prep_pack?: unknown };
        setRow({ id: app.id, company_name: app.company_name, role: app.role, status: app.status, job_description: app.job_description });
        setPack(packFromRow(app.prep_pack));
        if (typeof data.warning === "string") setWarning(data.warning);
        setLoad("ready");
      } catch {
        if (!active) return;
        setError("Couldn't reach the server. Check your connection and try again.");
        setLoad("error");
      }
      getUsage().then((u) => { if (active) setUsage(u); });
    }
    run();
    return () => { active = false; };
  }, [id]);

  // Ratings belong to a specific pack; a regenerated pack starts clean.
  useEffect(() => {
    if (!userId || !pack) return;
    setRatings(loadPrepProgress(userId, id, pack.generatedAt));
  }, [userId, id, pack]);

  const onRate = useCallback(
    (questionId: string, rating: PrepRating) => {
      setRatings((prev) => {
        const next = { ...prev, [questionId]: rating };
        if (userId && pack) savePrepProgress(userId, id, pack.generatedAt, next);
        return next;
      });
    },
    [userId, id, pack]
  );

  // Practice exit returns focus to the button that opened it.
  useEffect(() => {
    if (!practicing && restoreFocus.current) {
      restoreFocus.current = false;
      practiceBtnRef.current?.focus();
    }
  }, [practicing]);

  useEffect(() => {
    if (!generating) return;
    setElapsed(0);
    const timer = setInterval(() => setElapsed((s) => s + 1), 1000);
    return () => clearInterval(timer);
  }, [generating]);

  // ── Generate / regenerate (one tailor credit; a cached pack is free) ────────
  async function generate(force: boolean) {
    if (generating) return;
    setError("");
    setErrorType(null);
    setWarning("");
    setGenerating(true);
    try {
      const res = await fetch("/api/prep", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ applicationId: id, ...(force ? { force: true } : {}) }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.status === 401) { setLoad("expired"); return; }
      if (!res.ok) {
        setError(data.error || "Couldn't build your prep pack. Try again.");
        setErrorType(typeof data.errorType === "string" ? data.errorType : null);
        return;
      }
      const fresh = packFromRow(data.pack);
      if (!fresh) { setError("The prep pack came back in an unexpected shape. Try again."); return; }
      setPack(fresh);
      setPracticing(false);
      if (typeof data.warning === "string") setWarning(data.warning);
    } catch {
      setError("Couldn't reach the server. Check your connection and try again.");
    } finally {
      setGenerating(false);
      getUsage().then(setUsage);
    }
  }

  async function downloadPdf() {
    if (!pack || pdfBusy) return;
    setPdfBusy(true);
    setPdfError("");
    try {
      const res = await fetch("/api/prep-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pack }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setPdfError(data.error || "Couldn't build the PDF. Try again.");
        return;
      }
      saveBlob(await res.blob(), prepPdfFilename(pack));
    } catch {
      setPdfError("Couldn't reach the server. Try again.");
    } finally {
      setPdfBusy(false);
    }
  }

  const quotaExhausted = !!usage && !usage.unlimited && usage.dailyUsed >= usage.dailyLimit;
  const remaining = usage ? Math.max(0, usage.dailyLimit - usage.dailyUsed) : null;
  const hasJd = !!row?.job_description?.trim();

  function renderError() {
    if (!error) return null;
    switch (errorType) {
      case "needs_cv":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Save your master CV first.</div>
            <div className="limitNotice__body">Every answer in the pack is built from it — there is nothing to build from yet.</div>
            <Button href="/customize" className="limitNotice__cta">Go to Customize →</Button>
          </div>
        );
      case "needs_jd":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Add the job description first.</div>
            <div className="limitNotice__body">The prep pack is built from it. Paste it into this application in the tracker, then come back.</div>
            <Button href="/applications" className="limitNotice__cta">Open the tracker →</Button>
          </div>
        );
      case "needs_keys":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Your 3 free tailors are used up.</div>
            <div className="limitNotice__body">Add your own key to keep going — it takes 2 minutes and the tool stays free.</div>
            <Button href="/settings" className="limitNotice__cta">Add your key in Settings →</Button>
          </div>
        );
      case "needs_openrouter_key":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Your Gemini key can&apos;t run interview prep.</div>
            <div className="limitNotice__body">Once your free Claude credits are used, prep runs on an OpenRouter key. Add one in Settings to continue.</div>
            <Button href="/settings" className="limitNotice__cta">Add an OpenRouter key →</Button>
          </div>
        );
      case "key_decrypt_failed":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Your API key needs to be re-entered.</div>
            <div className="limitNotice__body">Your saved key can no longer be read. Please go to Settings and replace it.</div>
            <Button href="/settings" className="limitNotice__cta">Go to Settings →</Button>
          </div>
        );
      case "user_key_limit":
        return (
          <div className="limitNotice" role="alert">
            <div className="limitNotice__title">Your key&apos;s daily limit is reached.</div>
            <div className="limitNotice__body">Its free quota resets daily — come back tomorrow to continue.</div>
          </div>
        );
      default:
        return <div className="limitNotice" role="alert">{error}</div>;
    }
  }

  const generatingBlock = generating && (
    <section className="loading" aria-live="polite">
      <div className="pulse" aria-hidden="true" />
      <ul>
        {STAGES.map((s) => (
          <li key={s}>{s}</li>
        ))}
      </ul>
      <p className="cvHelp">Usually 20–40 seconds · {elapsed}s</p>
    </section>
  );

  return (
    <main className="page">
      <div className="container">
        <AppHeader
          title="Interview prep"
          tagline={
            row
              ? `${row.role} at ${row.company_name} — answers built only from your real CV, each traced back to the line it came from.`
              : "Answers built only from your real CV, each traced back to the line it came from."
          }
        />
        <p className="prepBack">
          <Link href="/applications" className="inlineLink">← Back to applications</Link>
        </p>

        {load === "loading" && (
          <Card>
            <Skeleton lines={4} label="Loading your prep pack" />
          </Card>
        )}

        {load === "expired" && (
          <Card>
            <StatusText role="alert">{SESSION_EXPIRED}</StatusText>
            <div className="actions">
              <Button href={`/auth/login?next=/applications/${id}/prep`}>Sign in</Button>
            </div>
          </Card>
        )}

        {load === "missing" && (
          <Card>
            <EmptyState title="This application doesn't exist" actions={<Button href="/applications">Back to applications</Button>}>
              It may have been deleted, or the link is wrong.
            </EmptyState>
          </Card>
        )}

        {load === "error" && (
          <Card>
            <StatusText role="alert">{error}</StatusText>
          </Card>
        )}

        {load === "ready" && row && !pack && !hasJd && (
          <Card>
            <EmptyState title="Add the job description first" actions={<Button href="/applications">Open the tracker</Button>}>
              The prep pack is built from the job description. Paste it into this application&apos;s JD cell in the tracker, then come back here.
            </EmptyState>
          </Card>
        )}

        {load === "ready" && row && !pack && hasJd && (
          <Card variant="dashed" className="prepHero">
            <div className="label">What you&apos;ll get</div>
            <ul>
              <li>8–10 likely questions for this exact role: behavioral, technical, motivation, company — and the honest gaps they&apos;ll probe.</li>
              <li>A STAR answer for each, built only from your master CV, with the CV lines it came from and a ✓ when they trace verbatim.</li>
              <li>Questions worth asking them, and a 30-second opener.</li>
              <li>Practice mode: one question at a time, reveal the answer, rate yourself, review the shaky ones.</li>
            </ul>
            {generatingBlock}
            {!generating && (
              <div className="actions" style={{ marginTop: 0 }}>
                <Button onClick={() => generate(false)} disabled={quotaExhausted}>
                  Generate prep pack
                </Button>
              </div>
            )}
            <p className="prepCost">
              Uses 1 tailor credit · saved to this application, so opening it again is free.
              {usage && !usage.unlimited && remaining !== null && ` ${remaining} of ${usage.dailyLimit} tailors left today.`}
            </p>
            {quotaExhausted && (
              <StatusText className="msgBelow" role="status">
                You&apos;ve used today&apos;s {usage?.dailyLimit} tailors — come back tomorrow, or add your own key in Settings.
              </StatusText>
            )}
            {renderError()}
          </Card>
        )}

        {load === "ready" && row && pack && (
          <>
            <div className="prepHead">
              <span className="prepHeadMeta">
                <Badge variant="pill">{row.status}</Badge>
                <span>Generated {formatGenerated(pack.generatedAt)}</span>
              </span>
              <div className="prepHeadActions">
                {confirmRegen ? (
                  <>
                    <span className="prepCost" style={{ marginTop: 0 }}>Regenerating uses 1 credit and resets your ratings.</span>
                    <Button variant="secondary" onClick={() => { setConfirmRegen(false); generate(true); }} disabled={generating}>
                      Confirm
                    </Button>
                    <Button variant="ghost" onClick={() => setConfirmRegen(false)} disabled={generating}>
                      Cancel
                    </Button>
                  </>
                ) : (
                  <Button variant="ghost" onClick={() => setConfirmRegen(true)} disabled={generating}>
                    Regenerate…
                  </Button>
                )}
                <Button variant="secondary" onClick={downloadPdf} disabled={pdfBusy || generating}>
                  {pdfBusy ? "Preparing…" : "Download PDF"}
                </Button>
                {!practicing && (
                  <Button ref={practiceBtnRef} onClick={() => setPracticing(true)} disabled={generating}>
                    Practice
                  </Button>
                )}
              </div>
            </div>
            {warning && <div className="limitNotice" role="status">{warning}</div>}
            {pdfError && <StatusText role="alert">{pdfError}</StatusText>}
            {generatingBlock}
            {!generating && renderError()}
            {!generating && practicing && (
              <PracticeMode
                pack={pack}
                ratings={ratings}
                onRate={onRate}
                onExit={() => {
                  restoreFocus.current = true;
                  setPracticing(false);
                }}
              />
            )}
            {!generating && !practicing && (
              <Card>
                <PrepPackView pack={pack} ratings={ratings} />
              </Card>
            )}
          </>
        )}
      </div>
    </main>
  );
}
