-- Stage 4: Interview prep. One prep pack per application, generated by
-- /api/prep (one metered model call) and cached here so re-opening it is free.
--
-- Shape (src/lib/prepPack.ts, version 1):
--   { version, generatedAt, company, role,
--     angle: { headline, whyYou[], honestGaps[{gap, howToAddress}] },
--     questions[{ id, category, question, whyTheyAsk, star|null, points[],
--                 evidence[{text, verified}], unverifiedNumbers[] }],
--     questionsToAsk[], opener, sources{jd, tailoredCv, research, talkingPoints} }
--
-- NULL = no pack yet. Existing RLS (auth.uid() = user_id, all four verbs)
-- covers the column. Only /api/prep writes it; the tracker PUT whitelist never
-- includes it. Code degrades until this is applied: reads retry without the
-- column (42703) and a generated pack is returned unsaved with a warning
-- (PGRST204) — same pattern as tailored_cv.
alter table public.applications
  add column if not exists prep_pack jsonb;
